var class_json={
    "resultCode":200,
    "resultMessage":"ok",
    "data":[
        {
            "id":"1",
            "classname":"移动2班"
        },
        {
            "id":"2",
            "classname":"软信2班"
        }
    ]
}




var students_json_01={
          "resultCode":200,
          "resultMessage":"ok",
          "data":[
            {
              "id":"1",
              "sno":"001",
              "truename":"baekhyun",
              "age":"27",
              "gender":"m",
              "tel":"156792963263",
              "major":"舞蹈",
              "classid":"1"
            },
            {
              "id":"2",
              "sno":"002",
              "truename":"chanyole",
              "age":"27",
              "gender":"m",
              "tel":"156792963263",
              "major":"舞蹈",
              "classid":"1"
            },
            {
              "id":"3",
              "sno":"003",
              "truename":"v",
              "age":"27",
              "gender":"m",
              "tel":"156792963263",
              "major":"舞蹈",
              "classid":"1"
            }
    ]
  };
var students_json_02={
    "resultCode":200,
    "resultMessage":"ok",
    "data":[
      {
        "id":"1",
        "sno":"001",
        "truename":"kai",
        "age":"27",
        "gender":"m",
        "tel":"156792963263",
        "major":"舞蹈",
        "classid":"1"
      },
      {
        "id":"2",
        "sno":"002",
        "truename":"sehun",
        "age":"27",
        "gender":"m",
        "tel":"156792963263",
        "major":"舞蹈",
        "classid":"1"
      },
      {
        "id":"3",
        "sno":"003",
        "truename":"lay",
        "age":"27",
        "gender":"m",
        "tel":"156792963263",
        "major":"舞蹈",
        "classid":"1"
      }
    ]
  };